### PR TITLE
Add pre-commit badge to README.md

### PR DESCRIPTION
**Pull request by ab5424**

### CODE REVIEW

**Comment by ab5424** [comment]
@adrianusler There are a few errors in the pre-commit, do you have a quick fix for them?

```
src/molara/Gui/supercell_dialog.py:75: error: Unsupported target for indexed assignment ("Sequence[int]")  [index]
src/molara/Gui/supercell_dialog.py:76: error: Unsupported target for indexed assignment ("Sequence[int]")  [index]
src/molara/Gui/supercell_dialog.py:77: error: Unsupported target for indexed assignment ("Sequence[int]")  [index]
src/molara/Gui/structure_widget.py:354: error: "Structure" has no attribute "basis_vectors"  [attr-defined]
src/molara/Gui/measuring_tool_dialog.py:66: error: List item 0 has incompatible type "None"; expected "str"  [list-item]
src/molara/Gui/main_window.py:180: error: Incompatible return value type (got "None", expected "bool")  [return-value]
```

**Comment by ab5424** [comment]
@adrianusler @Michel-Heinz The remaining pre-commit failures are unrelated to this PR (they were triggered because of #321).

**Review by Michel-Heinz — APPROVED** [review]
I approve 👍
